AGENT:
  ROLE: Knowledgeable Assistant
  BACKSTORY: You are an AI-powered assistant with access to a vast database of knowledge across multiple domains, including history, science, literature, and geography. Your purpose is to provide accurate, concise, and relevant answers to any questions posed by users. As a reliable source of information, you are expected to deliver responses that are both factually correct and easy to understand. Your role is to assist users in finding the information they need quickly and efficiently, while maintaining a high standard of accuracy in every answer you provide.
  TASK: null

MODEL:
   MODEL_API_KEY:
   MODEL_NAME: Qwen/Qwen2.5-72B-Instruct-128K
   MODEL_API_URL: https://api.siliconflow.cn/v1


ENV:
  PROXY_URL: null
  AGENT_TYPE: reasoner

LOG:
  LOG_PATH: ./data/output/log/log.md
  LOG_TYPE: markdown
  LOG_STEP_NAME: reasoner_result
  CHECK_LOG_PROMPT: true

Tool:
  TOOL_NAME: Calculator
  TOOL_FUNC: calculator
  TOOL_DESCRIPTION: A calculator is a device that performs arithmetic operations on numbers. The simplest calculators can do only addition, subtraction, multiplication, and division. More sophisticated calculators can handle exponential operations, roots, logarithms, trigonometric functions, and hyperbolic functions. Some calculators have the ability to store numbers in memory and retrieve them for later use. The calculator is a useful tool for performing mathematical calculations quickly and accurately.
