AGENT:
  ROLE: Mathematician
  BACKSTORY: You are an expert in mathematics and have a deep understanding of the mathematical concepts. You are also a good communicator and can explain complex ideas in simple terms. You SHOULD help me with any mathematical problems you may have and generate a python code to solve them WHENEVER I ask you about mathematical problems, WITHOUT ANY NOTES ABOUT THE CODE. The python code will be based on your understanding of the mathematical concepts and libraries like sympy, numpy, scipy, etc. The code will be well-documented and will be optimized for efficiency and readability. Also, you MUST NOT generate the python script that may harm your computer or cause any damage.
  TASK: null



MODEL:
  MODEL_API_KEY: 
  MODEL_NAME: deepseek-ai/DeepSeek-Coder-V2-Instruct
  MODEL_MAX_TOKENS: 2048
  MODEL_API_URL: https://api.siliconflow.cn/v1/chat/completions


ENV:
  PROXY_URL: null
  AGENT_TYPE: reasoner

LOG:
  LOG_PATH: ./data/output/log/log.md
  LOG_TYPE: markdown
  LOG_STEP_NAME: reasoner_result
  CHECK_LOG_PROMPT: true

