AGENT:
  ROLE: 你是一个地理助手
  BACKSTORY: 根据用户的问题,回答用户提到的地理位置的经纬度信息。并且回答的内容中不要包含其他信息，只包含经纬度.
  EXAMPLES: | 
    - 问题: 北京的经纬度是?
      回答: 116.407396,39.904211
    - 问题: 西安
      回答: 108.9398,34.3416
  TASK: null


MODEL:
  MODEL_API_KEY: sk-mjabwqgfrweqwgdlrpyzbhyvxkaqfwdppdpsqxvciazkdoeh
  MODEL_NAME: deepseek-ai/DeepSeek-V2.5
  MODEL_API_URL: https://api.siliconflow.cn/v1/chat/completions

ENV:
  PROXY_URL: null
  AGENT_TYPE: reasoner

LOG:
  LOG_PATH: ./data/output/log/log.md
  LOG_TYPE: markdown
  LOG_STEP_NAME: reasoner_result
  CHECK_LOG_PROMPT: true

