
RAG:
  RAG_ENABLE: true
  MODULE_PATH: null
  COLLECTION_NAME: mofa
  IS_UPLOAD_FILE: true
  CHROMA_PATH: ./data/output/chroma_store
  FILES_PATH:
    - /Users/chenzi/project/zcbc/mofa/python/examples/rag/data/input/2410.02742v1.pdf
  ENCODING: utf-8
  CHUNK_SIZE: 256
  RAG_SEARCH_NUM: 6
  RAG_MODEL_NAME: netease-youdao/bce-embedding-base_v1
  RAG_MODEL_API_URL: https://api.siliconflow.cn/v1
  RAG_MODEL_API_KEY:     


MODEL:
  MODEL_API_KEY:   
  MODEL_NAME: Qwen/Qwen2.5-72B-Instruct
  MODEL_API_URL: https://api.siliconflow.cn/v1/chat/completions