[tool.poetry]
name = "mofa_search"
version = "0.1.1"
authors = [
    "ZhongHuan Wu",
    "Cheng Chen"
]
description = "About using agent for network query"
license = "MIT License"
homepage = "https://github.com/moxin-org/mofa"
documentation = "https://github.com/moxin-org/Moxin-App-Engine/mae/agent-hub/query-assistant/README.md"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
pydantic = "^1.10.2"
selenium = "^4.5.0"
beautifulsoup4 = "^4.11.1"
trafilatura = "^1.1.0"
openai = "^0.27.0"
numpy = "<2.0.0"
pyarrow = ">=5.0.0"
chromedriver-autoinstaller = ">^0.6.3"
crawl4ai = "^0.3.73"

[tool.poetry.scripts]
llm = "llm.main:main"

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"

[project]
readme = "README.md"
