nodes:
  - id: terminal-input
    build: pip install -e ../../node-hub/terminal-input
    path: dynamic
    outputs:
      - data
    inputs:
      load_url_connector_response: load-url-agent/load_url_connector_response
      discovery_search_box_response: discovery-search-box-agent/discovery_search_box_response

  - id: load-url-agent
    operator:
      python: ./scripts/load_url_connector_agent.py
      inputs:
        url: terminal-input/data
      outputs:
        - load_url_connector_response
  - id: discovery-search-box-agent
    operator:
      python: scripts/discovery_search_box_agent.py
      inputs:
        load_url_connector_response: load-url-agent/load_url_connector_response
      outputs:
        - discovery_search_box_response

