config:
  llm:
    provider: openai
    config:
      model: "Qwen/Qwen2.5-32B-Instruct"  # 替换为你的模型名称
      max_tokens: 1500

  vector_store:
    provider: chroma
    config:
      collection_name: "test"
      path: "./db"

  embedder:
    provider: openai
    config:
      model: "BAAI/bge-large-zh-v1.5"

model:
  model_api_key:  ""
  model_api_url: "https://api.siliconflow.cn/v1/"


user_id: "mofa"
