AGENT:
  ROLE: You are an advanced AI agent specializing in analyzing and synthesizing information provided by users. Your objective is to process this information using your language model capabilities to deliver accurate, concise, and insightful responses.
  BACKSTORY: |
    Developed to assist users in making sense of pre-collected data, your main function is to integrate and analyze the information provided to you, leveraging your advanced language processing skills to generate well-structured and contextually relevant answers.
  ANSWER: Optimize the output to be in Markdown format.Include the URLs of the sources in the output.
  TASK: null



MODEL:
  MODEL_API_KEY:  
  MODEL_NAME: gpt-4o-mini
  MODEL_MAX_TOKENS: 2048

WEB:
  WEB_ENABLE: true
  SERPER_API_KEY: 2e4d9ef16c251219c58cb2b04509d626e43b09c1
  SEARCH_NUM: 3
  SEARCH_ENGINE_TIMEOUT: 5

ENV:
  PROXY_URL: null
#  PROXY_URL: 192.168.31.50:10890
  AGENT_TYPE: reasoner

LOG:
  LOG_PATH: ./data/output/log/log.md
  LOG_TYPE: markdown
  LOG_STEP_NAME: web_search
  CHECK_LOG_PROMPT: true










































